import React from "react";
import {
  Article,
  Browsers,
  ChartBar,
  ChartLineUp,
  ChatCircleDots,
  Code,
  Compass,
  Crown,
  Cpu,
  CurrencyInr,
  DeviceMobile,
  FileText,
  FolderUser,
  Gear,
  GlobeHemisphereWest,
  Handshake,
  IdentificationCard,
  Lightning,
  MagnifyingGlass,
  MapPin,
  Megaphone,
  PresentationChart,
  Receipt,
  Robot,
  RocketLaunch,
  ShareNetwork,
  ShieldCheck,
  ShoppingBag,
  Sparkle,
  Storefront,
  SuitcaseSimple,
  Table,
  Tag,
  Target,
  TrendUp,
  Users,
  WhatsappLogo,
} from "@phosphor-icons/react/dist/ssr";

const iconMap: Record<string, React.ComponentType<{ weight?: "duotone" | "bold" | "regular" | "fill" | "thin" | "light"; className?: string }>> = {
  Article,
  Browsers,
  ChartBar,
  ChartLineUp,
  ChatCircleDots,
  Code,
  Compass,
  Crown,
  Cpu,
  CurrencyInr,
  DeviceMobile,
  FileText,
  FolderUser,
  Gear,
  GlobeHemisphereWest,
  Handshake,
  IdentificationCard,
  Lightning,
  MagnifyingGlass,
  MapPin,
  Megaphone,
  PresentationChart,
  Receipt,
  Robot,
  RocketLaunch,
  ShareNetwork,
  ShieldCheck,
  ShoppingBag,
  Sparkle,
  Storefront,
  SuitcaseSimple,
  Table,
  Tag,
  Target,
  TrendUp,
  Users,
  WhatsappLogo,
};

export default function ProductIcon({
  name,
  weight = "duotone",
  className,
}: {
  name: string;
  weight?: "duotone" | "bold" | "regular" | "fill" | "thin" | "light";
  className?: string;
}) {
  const IconComponent = iconMap[name] || Target;
  return <IconComponent weight={weight} className={className} />;
}
